/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import java.util.ArrayList;
import modelo.Modelo;


public class VistaPrincipal extends javax.swing.JFrame implements Vista {

    Controlador controlador;
    
    public VistaPrincipal() {
        initComponents();
        
        this.setVisible(true);
    }
    
    public void setControlador(Controlador c) {
        controlador=c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vistaColeccion = new javax.swing.JPanel();
        numero = new javax.swing.JTextField();
        botonAñade = new javax.swing.JButton();
        botonQuita = new javax.swing.JButton();
        vistaColeccion2 = new javax.swing.JPanel();
        botonAñade2 = new javax.swing.JButton();
        vistaColeccion3 = new javax.swing.JPanel();
        numero1 = new javax.swing.JTextField();
        botonAñadirEvaluacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        vistaColeccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        numero.setText("0");

        botonAñade.setText("Añade");
        botonAñade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadeActionPerformed(evt);
            }
        });

        botonQuita.setText("Quita");
        botonQuita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonQuitaActionPerformed(evt);
            }
        });

        vistaColeccion2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        botonAñade2.setText("Añade");
        botonAñade2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñade2ActionPerformed(evt);
            }
        });

        vistaColeccion3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        numero1.setText("0");

        botonAñadirEvaluacion.setText("Añade Evaluacion");
        botonAñadirEvaluacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirEvaluacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonQuita)
                            .addComponent(botonAñade)
                            .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonAñade2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonAñadirEvaluacion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(vistaColeccion, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
                        .addComponent(vistaColeccion2, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE))
                    .addComponent(vistaColeccion3, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vistaColeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonAñade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonQuita)
                        .addGap(17, 17, 17)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(botonAñade2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(vistaColeccion2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(vistaColeccion3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(numero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonAñadirEvaluacion)
                        .addGap(60, 60, 60))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAñadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadeActionPerformed
        Integer i=Integer.parseInt(this.numero.getText());
        controlador.añadeElemento(i);
    }//GEN-LAST:event_botonAñadeActionPerformed

    private void botonQuitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonQuitaActionPerformed
        controlador.quitaUno();
    }//GEN-LAST:event_botonQuitaActionPerformed

    private void botonAñade2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñade2ActionPerformed
        Integer i=Integer.parseInt(this.numero.getText());
        controlador.añadeElemento2(i);
    }//GEN-LAST:event_botonAñade2ActionPerformed

    private void botonAñadirEvaluacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirEvaluacionActionPerformed
        // TODO add your handling code here:
         Integer i=Integer.parseInt(this.numero1.getText());
         controlador.añadeElemento(i);
        controlador.añadeElemento2(i);
        controlador.añadeElemento3(i);
    }//GEN-LAST:event_botonAñadirEvaluacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }
    
    public void recibeModelo(Modelo m) {
        
        ArrayList<Integer> coleccion=m.getColeccion1();
        ArrayList<Integer> coleccion2=m.getColeccion2();
        ArrayList<Integer> coleccion3=m.getColeccion3();
        
        this.vistaColeccion.removeAll();
        for(Integer i:coleccion) {
            VistaElemento ve=new VistaElemento();
            ve.recibeModelo(i);
            this.vistaColeccion.add(ve);
        }
        
        this.vistaColeccion2.removeAll();
        for(Integer i:coleccion2) {
            VistaElemento ve=new VistaElemento();
            ve.recibeModelo(i);
            this.vistaColeccion2.add(ve);
        }
        
        this.vistaColeccion3.removeAll();
        for(Integer i:coleccion3) {
            VistaElemento ve=new VistaElemento();
            ve.recibeModelo(i);
            this.vistaColeccion3.add(ve);
        }
        repaint();
        revalidate();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAñade;
    private javax.swing.JButton botonAñade2;
    private javax.swing.JButton botonAñadirEvaluacion;
    private javax.swing.JButton botonQuita;
    private javax.swing.JTextField numero;
    private javax.swing.JTextField numero1;
    private javax.swing.JPanel vistaColeccion;
    private javax.swing.JPanel vistaColeccion2;
    private javax.swing.JPanel vistaColeccion3;
    // End of variables declaration//GEN-END:variables
}
