/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import javax.swing.JTextField;


public class VistaElemento extends javax.swing.JPanel {

    /**
     * Creates new form VistaElemento
     */
    public VistaElemento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numeroTexto = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(30, 30));
        setLayout(new java.awt.BorderLayout());

        numeroTexto.setEditable(false);
        numeroTexto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        numeroTexto.setText("jTextField1");
        numeroTexto.setBorder(null);
        numeroTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroTextoActionPerformed(evt);
            }
        });
        add(numeroTexto, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents

    private void numeroTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroTextoActionPerformed

    public void recibeModelo(Integer i) {
        //this.numero.setText(i.toString());
        this.numeroTexto.setText(i.toString());
        this.numeroTexto.setHorizontalAlignment(JTextField.CENTER);
        Integer doble = i*2;
       // this.numeroLabel.setText(doble.toString());
       //this.numeroLabel.setForeground(Color.red);
        repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField numeroTexto;
    // End of variables declaration//GEN-END:variables
}
