/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.Casilla;
import civitas.CasillaCalle;
import civitas.CasillaSorpresa;
import civitas.CivitasJuego;
import civitas.Diario;
import civitas.GestionInmobiliaria;
import civitas.Jugador;
import civitas.OperacionInmobiliaria;
import civitas.OperacionJuego;
import controladorCivitas.Respuesta;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import GUI.Vista;

/**
 *
 * @author carlo
 */
public class CivitasView extends javax.swing.JFrame implements Vista {

    /**
     * Creates new form CivitasView
     */
    CivitasJuego juego;
    ArrayList<CasillaPanel> casillas;
    Border bordePorDefecto = new LineBorder(Color.BLACK, 3, false);
    Border bordeCasillaSeleccionada = new LineBorder(Color.GRAY, 3, false);
    
    public CivitasView() {
        initComponents();
        juego = null;
        
        casillas = new ArrayList<>();
        casillas.add(casillaPanel1);
        casillas.add(casillaPanel2);
        casillas.add(casillaPanel3);
        casillas.add(casillaPanel4);
        casillas.add(casillaPanel5);
        casillas.add(casillaPanel6);
        casillas.add(casillaPanel7);
        casillas.add(casillaPanel8);
        casillas.add(casillaPanel9);
        casillas.add(casillaPanel10);
        casillas.add(casillaPanel11);
        casillas.add(casillaPanel12);
        casillas.add(casillaPanel13);
        casillas.add(casillaPanel14);
        casillas.add(casillaPanel15);
        casillas.add(casillaPanel16);
        casillas.add(casillaPanel17);
        casillas.add(casillaPanel18);
        casillas.add(casillaPanel19);
        casillas.add(casillaPanel20);
        
        panelJugador1.setBackground(Jugador.getColorJugador1());
        panelJugador2.setBackground(Jugador.getColorJugador2());
        panelJugador3.setBackground(Jugador.getColorJugador3());
        panelJugador4.setBackground(Jugador.getColorJugador4());
        
        Dado.createInstance(this);
            
    }

    public void setCivitasJuego(CivitasJuego juego) {
        this.juego = juego;

        /* 
        
        ArrayList<Casilla> casillasAux = juego.getTablero().getCasillas();
        int aux = casillasAux.size()/4;
        for (int i = 0; i < casillasAux.size(); i++){
            CasillaPanel casilla = new CasillaPanel(casillasAux.get(i));
            
            casillas.add(casilla);
            this.getContentPane().add(casilla); 
            
            casilla.setLocation((i+1)*216, 100);
            casilla.setSize(216, 216);
            casilla.setVisible(true);
            
            
           
            repaint();
            revalidate();
        }
         */
       
        
        this.textJugador1.setText(juego.getJugadores().get(0).getNombre());
        this.textJugador2.setText(juego.getJugadores().get(1).getNombre());
        this.textJugador3.setText(juego.getJugadores().get(2).getNombre());
        this.textJugador4.setText(juego.getJugadores().get(3).getNombre());
        

        this.setVisible(true);

        repaint();
        revalidate();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        jugadorPanel = new GUI.JugadorPanel();
        panelRanking = new javax.swing.JPanel();
        panelPrimerPuesto = new javax.swing.JPanel();
        panelNombrePrimerPuesto = new javax.swing.JPanel();
        labelNombrePrimerPuesto = new javax.swing.JLabel();
        textNombrePrimerPuesto = new javax.swing.JTextField();
        panelSaldoPrimerPuesto = new javax.swing.JPanel();
        labelSaldoPrimerPuesto = new javax.swing.JLabel();
        textSaldoPrimerPuesto = new javax.swing.JTextField();
        panelSegundoPuesto = new javax.swing.JPanel();
        panelNombreSegundoPuesto = new javax.swing.JPanel();
        labelSegundoPuesto = new javax.swing.JLabel();
        textNombreSegundoPuesto = new javax.swing.JTextField();
        panelSaldoSegundoPuesto = new javax.swing.JPanel();
        labelSaldoSegundoPuesto = new javax.swing.JLabel();
        textSaldoSegundoPuesto = new javax.swing.JTextField();
        panelTercerPuesto = new javax.swing.JPanel();
        panelNombreTercerPuesto = new javax.swing.JPanel();
        labelTercerPuesto = new javax.swing.JLabel();
        textNombreTercerPuesto = new javax.swing.JTextField();
        panelSaldoTercerPuesto = new javax.swing.JPanel();
        labelSaldoTercerPuesto = new javax.swing.JLabel();
        textSaldoTercerPuesto = new javax.swing.JTextField();
        panelCuartoPuesto = new javax.swing.JPanel();
        panelNombreCuartoPuesto = new javax.swing.JPanel();
        labelCuartoPuesto = new javax.swing.JLabel();
        textNombreCuartoPuesto = new javax.swing.JTextField();
        panelSaldoCuartoPuesto = new javax.swing.JPanel();
        labelSaldoCuartoPuesto = new javax.swing.JLabel();
        textSaldoCuartoPuesto = new javax.swing.JTextField();
        panelSiguienteOperacion = new javax.swing.JPanel();
        siguienteOperacionLabel = new javax.swing.JLabel();
        siguienteOperacionTextField = new javax.swing.JTextField();
        casillaPanel1 = new GUI.CasillaPanel();
        casillaPanel2 = new GUI.CasillaPanel();
        casillaPanel3 = new GUI.CasillaPanel();
        casillaPanel4 = new GUI.CasillaPanel();
        casillaPanel5 = new GUI.CasillaPanel();
        casillaPanel6 = new GUI.CasillaPanel();
        casillaPanel7 = new GUI.CasillaPanel();
        casillaPanel8 = new GUI.CasillaPanel();
        casillaPanel9 = new GUI.CasillaPanel();
        casillaPanel10 = new GUI.CasillaPanel();
        casillaPanel11 = new GUI.CasillaPanel();
        casillaPanel12 = new GUI.CasillaPanel();
        casillaPanel13 = new GUI.CasillaPanel();
        casillaPanel14 = new GUI.CasillaPanel();
        casillaPanel15 = new GUI.CasillaPanel();
        casillaPanel16 = new GUI.CasillaPanel();
        casillaPanel17 = new GUI.CasillaPanel();
        casillaPanel18 = new GUI.CasillaPanel();
        casillaPanel19 = new GUI.CasillaPanel();
        casillaPanel20 = new GUI.CasillaPanel();
        panelJugador2 = new javax.swing.JPanel();
        labelJugador2 = new javax.swing.JLabel();
        textJugador2 = new javax.swing.JTextField();
        panelJugador4 = new javax.swing.JPanel();
        labelJugador4 = new javax.swing.JLabel();
        textJugador4 = new javax.swing.JTextField();
        panelJugador3 = new javax.swing.JPanel();
        labelJugador3 = new javax.swing.JLabel();
        textJugador3 = new javax.swing.JTextField();
        panelJugador1 = new javax.swing.JPanel();
        labelJugador1 = new javax.swing.JLabel();
        textJugador1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Civitas Carlos García Segura");

        Titulo.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        Titulo.setText("CIVITAS");

        jugadorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "JUGADOR ACTUAL", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP));

        panelRanking.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ranking", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        panelRanking.setLayout(new javax.swing.BoxLayout(panelRanking, javax.swing.BoxLayout.Y_AXIS));

        labelNombrePrimerPuesto.setText("Primer Puesto:");
        panelNombrePrimerPuesto.add(labelNombrePrimerPuesto);

        textNombrePrimerPuesto.setEditable(false);
        panelNombrePrimerPuesto.add(textNombrePrimerPuesto);

        panelPrimerPuesto.add(panelNombrePrimerPuesto);

        labelSaldoPrimerPuesto.setText("Saldo:");
        panelSaldoPrimerPuesto.add(labelSaldoPrimerPuesto);

        textSaldoPrimerPuesto.setEditable(false);
        panelSaldoPrimerPuesto.add(textSaldoPrimerPuesto);

        panelPrimerPuesto.add(panelSaldoPrimerPuesto);

        panelRanking.add(panelPrimerPuesto);

        labelSegundoPuesto.setText("Segundo Puesto:");
        panelNombreSegundoPuesto.add(labelSegundoPuesto);

        textNombreSegundoPuesto.setEditable(false);
        textNombreSegundoPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreSegundoPuestoActionPerformed(evt);
            }
        });
        panelNombreSegundoPuesto.add(textNombreSegundoPuesto);

        panelSegundoPuesto.add(panelNombreSegundoPuesto);

        labelSaldoSegundoPuesto.setText("Saldo:");
        panelSaldoSegundoPuesto.add(labelSaldoSegundoPuesto);

        textSaldoSegundoPuesto.setEditable(false);
        panelSaldoSegundoPuesto.add(textSaldoSegundoPuesto);

        panelSegundoPuesto.add(panelSaldoSegundoPuesto);

        panelRanking.add(panelSegundoPuesto);

        labelTercerPuesto.setText("Tercer Puesto:");
        panelNombreTercerPuesto.add(labelTercerPuesto);

        textNombreTercerPuesto.setEditable(false);
        panelNombreTercerPuesto.add(textNombreTercerPuesto);

        panelTercerPuesto.add(panelNombreTercerPuesto);

        labelSaldoTercerPuesto.setText("Saldo:");
        panelSaldoTercerPuesto.add(labelSaldoTercerPuesto);

        textSaldoTercerPuesto.setEditable(false);
        panelSaldoTercerPuesto.add(textSaldoTercerPuesto);

        panelTercerPuesto.add(panelSaldoTercerPuesto);

        panelRanking.add(panelTercerPuesto);

        labelCuartoPuesto.setText("Cuarto Puesto:");
        panelNombreCuartoPuesto.add(labelCuartoPuesto);

        textNombreCuartoPuesto.setEditable(false);
        textNombreCuartoPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreCuartoPuestoActionPerformed(evt);
            }
        });
        panelNombreCuartoPuesto.add(textNombreCuartoPuesto);

        panelCuartoPuesto.add(panelNombreCuartoPuesto);

        labelSaldoCuartoPuesto.setText("Saldo:");
        panelSaldoCuartoPuesto.add(labelSaldoCuartoPuesto);

        textSaldoCuartoPuesto.setEditable(false);
        panelSaldoCuartoPuesto.add(textSaldoCuartoPuesto);

        panelCuartoPuesto.add(panelSaldoCuartoPuesto);

        panelRanking.add(panelCuartoPuesto);

        siguienteOperacionLabel.setText("Siguiente Operacion:");
        panelSiguienteOperacion.add(siguienteOperacionLabel);

        siguienteOperacionTextField.setEditable(false);
        siguienteOperacionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteOperacionTextFieldActionPerformed(evt);
            }
        });
        panelSiguienteOperacion.add(siguienteOperacionTextField);

        labelJugador2.setText("Jugador 2:");
        panelJugador2.add(labelJugador2);

        textJugador2.setEditable(false);
        panelJugador2.add(textJugador2);

        labelJugador4.setText("Jugador 4:");
        panelJugador4.add(labelJugador4);

        textJugador4.setEditable(false);
        panelJugador4.add(textJugador4);

        labelJugador3.setText("Jugador 3:");
        panelJugador3.add(labelJugador3);

        textJugador3.setEditable(false);
        panelJugador3.add(textJugador3);

        labelJugador1.setText("Jugador 1:");
        panelJugador1.add(labelJugador1);

        textJugador1.setEditable(false);
        panelJugador1.add(textJugador1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(casillaPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(casillaPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(casillaPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(casillaPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(casillaPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(casillaPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casillaPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casillaPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(casillaPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casillaPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casillaPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casillaPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(296, 296, 296)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panelSiguienteOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(panelJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(panelJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(panelJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(panelJugador4, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(panelRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(casillaPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(casillaPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(casillaPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(casillaPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(casillaPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casillaPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casillaPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(casillaPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jugadorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jugadorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(casillaPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casillaPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casillaPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casillaPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casillaPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casillaPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(panelSiguienteOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(panelJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelJugador4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(panelRanking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(casillaPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(casillaPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(casillaPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(casillaPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(casillaPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(casillaPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(casillaPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casillaPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(casillaPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casillaPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casillaPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casillaPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casillaPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casillaPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siguienteOperacionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteOperacionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_siguienteOperacionTextFieldActionPerformed

    private void textNombreSegundoPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreSegundoPuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreSegundoPuestoActionPerformed

    private void textNombreCuartoPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreCuartoPuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreCuartoPuestoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CivitasView().setVisible(true);
            }
        });
    }

    @Override
    public void actualiza() {
        jugadorPanel.setJugador(juego.getJugadorActual());
        //this.rankingLabel.setVisible(false);
        //this.rankingTextField.setVisible(false);
        
        if (juego.finalDelJuego()) {
            //this.rankingLabel.setVisible(true);
            //this.rankingTextField.setVisible(true);
            
            ArrayList<Jugador> jugadoresRanking = juego.ranking();
            
            /*
            String ranking = "";
            for (int i =0; i < jugadoresRanking.size(); i++){
                ranking+=jugadoresRanking.get(i).getNombre()+"\n";
            }
            this.rankingTextField.setText(ranking);
            */
            
            this.textNombrePrimerPuesto.setText(jugadoresRanking.get(0).getNombre());
            this.textNombreSegundoPuesto.setText(jugadoresRanking.get(1).getNombre());
            this.textNombreTercerPuesto.setText(jugadoresRanking.get(2).getNombre());
            this.textNombreCuartoPuesto.setText(jugadoresRanking.get(3).getNombre());
            
            
            this.panelPrimerPuesto.setBackground(jugadoresRanking.get(0).getColorJugador());
            this.panelSegundoPuesto.setBackground(jugadoresRanking.get(1).getColorJugador());
            this.panelTercerPuesto.setBackground(jugadoresRanking.get(2).getColorJugador());
            this.panelCuartoPuesto.setBackground(jugadoresRanking.get(3).getColorJugador());
            
        }
        
        for (int i = 0; i < casillas.size(); i++)
        {
            switch(i){
                case 0:
                    casillas.get(i).setCasilla(juego.getTablero().getCasillas().get(0));
                    break;
                case 5:
                    casillas.get(i).setCasilla((CasillaSorpresa) (juego.getTablero().getCasillas().get(5)));
                    break;
                case 10:
                    casillas.get(i).setCasilla(juego.getTablero().getCasillas().get(10));
                    break;
                case 15:
                    casillas.get(i).setCasilla((CasillaSorpresa) (juego.getTablero().getCasillas().get(15)));
                    break;
                default:
                    casillas.get(i).setCasilla((CasillaCalle) (juego.getTablero().getCasillas().get(i)));
                    
            }
            casillas.get(i).setBorder(bordePorDefecto);
        }
        
        
        casillas.get(juego.getJugadorActual().getCasillaActual()).setBorder(bordeCasillaSeleccionada);
        
        /*
        this.casillaPanel1.setCasilla(juego.getTablero().getCasillas().get(0));
        this.casillaPanel2.setCasilla((CasillaCalle) (juego.getTablero().getCasillas().get(1)));
        this.casillaPanel3.setCasilla((CasillaCalle) (juego.getTablero().getCasillas().get(2)));
        this.casillaPanel4.setCasilla((CasillaCalle) (juego.getTablero().getCasillas().get(3)));
        this.casillaPanel5.setCasilla((CasillaCalle) (juego.getTablero().getCasillas().get(4)));
        this.casillaPanel6.setCasilla((CasillaSorpresa) (juego.getTablero().getCasillas().get(5)));
        this.casillaPanel7.setCasilla((CasillaCalle) (juego.getTablero().getCasillas().get(6)));
        this.casillaPanel8.setCasilla((CasillaCalle) (juego.getTablero().getCasillas().get(7)));
        this.casillaPanel9.setCasilla((CasillaCalle) (juego.getTablero().getCasillas().get(8)));
        this.casillaPanel10.setCasilla((CasillaCalle) (juego.getTablero().getCasillas().get(9)));
        this.casillaPanel11.setCasilla(juego.getTablero().getCasillas().get(10));
        this.casillaPanel12.setCasilla((CasillaCalle) (juego.getTablero().getCasillas().get(11)));
        this.casillaPanel13.setCasilla((CasillaCalle) (juego.getTablero().getCasillas().get(12)));
        this.casillaPanel14.setCasilla((CasillaCalle) (juego.getTablero().getCasillas().get(13)));
        this.casillaPanel15.setCasilla((CasillaCalle) (juego.getTablero().getCasillas().get(14)));
        this.casillaPanel16.setCasilla((CasillaSorpresa) (juego.getTablero().getCasillas().get(15)));
        this.casillaPanel17.setCasilla((CasillaCalle) (juego.getTablero().getCasillas().get(16)));
        this.casillaPanel18.setCasilla((CasillaCalle) (juego.getTablero().getCasillas().get(17)));
        this.casillaPanel19.setCasilla((CasillaCalle) (juego.getTablero().getCasillas().get(18)));
        this.casillaPanel20.setCasilla((CasillaCalle) (juego.getTablero().getCasillas().get(19)));
        */
        repaint();
        revalidate();
    }

    @Override
    public void pausa() {
        int val = JOptionPane.showConfirmDialog(null, "¿Continuar?", "Siguiente Paso", JOptionPane.YES_NO_OPTION);
        if (val == 1) {
            System.exit(0);
        }
    }

    @Override
    public Respuesta comprar() {
        int opcion = 1 - JOptionPane.showConfirmDialog(null, "¿Quieres comprar la calle actual?", "Compra", JOptionPane.YES_NO_OPTION);
        Respuesta respuesta;
        if (opcion == 0) {
            respuesta = Respuesta.NO;
        } else {
            respuesta = Respuesta.SI;
        }
        return respuesta;
    }

    @Override
    public OperacionInmobiliaria elegirOperacion() {
        GestionarDialog gestion = new GestionarDialog(this);
        int respuesta = gestion.getGestion();
        return OperacionInmobiliaria.values()[respuesta];
    }

    @Override
    public int elegirPropiedad() {
        PropiedadDialog propiedad = new PropiedadDialog(this, juego.getJugadorActual());
        int respuesta = propiedad.getPropiedad();
        return respuesta;
    }

    @Override
    public void mostrarSiguienteOperacion(OperacionJuego operacion) {
        this.siguienteOperacionTextField.setText(operacion.toString());
        if (operacion == OperacionJuego.AVANZAR) {
            //DadoDialog.createInstance(this);
            //DadoDialog.getInstance().setVisible(true);
        }

        repaint();
        revalidate();
    }

    @Override
    public void mostrarEventos() {
        if (Diario.getInstance().eventosPendientes()) {
            DiarioDialog diarioD = new DiarioDialog(this);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private GUI.CasillaPanel casillaPanel1;
    private GUI.CasillaPanel casillaPanel10;
    private GUI.CasillaPanel casillaPanel11;
    private GUI.CasillaPanel casillaPanel12;
    private GUI.CasillaPanel casillaPanel13;
    private GUI.CasillaPanel casillaPanel14;
    private GUI.CasillaPanel casillaPanel15;
    private GUI.CasillaPanel casillaPanel16;
    private GUI.CasillaPanel casillaPanel17;
    private GUI.CasillaPanel casillaPanel18;
    private GUI.CasillaPanel casillaPanel19;
    private GUI.CasillaPanel casillaPanel2;
    private GUI.CasillaPanel casillaPanel20;
    private GUI.CasillaPanel casillaPanel3;
    private GUI.CasillaPanel casillaPanel4;
    private GUI.CasillaPanel casillaPanel5;
    private GUI.CasillaPanel casillaPanel6;
    private GUI.CasillaPanel casillaPanel7;
    private GUI.CasillaPanel casillaPanel8;
    private GUI.CasillaPanel casillaPanel9;
    private GUI.JugadorPanel jugadorPanel;
    private javax.swing.JLabel labelCuartoPuesto;
    private javax.swing.JLabel labelJugador1;
    private javax.swing.JLabel labelJugador2;
    private javax.swing.JLabel labelJugador3;
    private javax.swing.JLabel labelJugador4;
    private javax.swing.JLabel labelNombrePrimerPuesto;
    private javax.swing.JLabel labelSaldoCuartoPuesto;
    private javax.swing.JLabel labelSaldoPrimerPuesto;
    private javax.swing.JLabel labelSaldoSegundoPuesto;
    private javax.swing.JLabel labelSaldoTercerPuesto;
    private javax.swing.JLabel labelSegundoPuesto;
    private javax.swing.JLabel labelTercerPuesto;
    private javax.swing.JPanel panelCuartoPuesto;
    private javax.swing.JPanel panelJugador1;
    private javax.swing.JPanel panelJugador2;
    private javax.swing.JPanel panelJugador3;
    private javax.swing.JPanel panelJugador4;
    private javax.swing.JPanel panelNombreCuartoPuesto;
    private javax.swing.JPanel panelNombrePrimerPuesto;
    private javax.swing.JPanel panelNombreSegundoPuesto;
    private javax.swing.JPanel panelNombreTercerPuesto;
    private javax.swing.JPanel panelPrimerPuesto;
    private javax.swing.JPanel panelRanking;
    private javax.swing.JPanel panelSaldoCuartoPuesto;
    private javax.swing.JPanel panelSaldoPrimerPuesto;
    private javax.swing.JPanel panelSaldoSegundoPuesto;
    private javax.swing.JPanel panelSaldoTercerPuesto;
    private javax.swing.JPanel panelSegundoPuesto;
    private javax.swing.JPanel panelSiguienteOperacion;
    private javax.swing.JPanel panelTercerPuesto;
    private javax.swing.JLabel siguienteOperacionLabel;
    private javax.swing.JTextField siguienteOperacionTextField;
    private javax.swing.JTextField textJugador1;
    private javax.swing.JTextField textJugador2;
    private javax.swing.JTextField textJugador3;
    private javax.swing.JTextField textJugador4;
    private javax.swing.JTextField textNombreCuartoPuesto;
    private javax.swing.JTextField textNombrePrimerPuesto;
    private javax.swing.JTextField textNombreSegundoPuesto;
    private javax.swing.JTextField textNombreTercerPuesto;
    private javax.swing.JTextField textSaldoCuartoPuesto;
    private javax.swing.JTextField textSaldoPrimerPuesto;
    private javax.swing.JTextField textSaldoSegundoPuesto;
    private javax.swing.JTextField textSaldoTercerPuesto;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarEstado() {
        jugadorPanel.setJugador(juego.getJugadorActual());
        this.panelRanking.setVisible(false);
        //this.rankingLabel.setVisible(false);
        //this.rankingTextField.setVisible(false);
        
        if (juego.finalDelJuego()) {
            this.panelRanking.setVisible(true);
            //this.rankingLabel.setVisible(true);
            //this.rankingTextField.setVisible(true);
            
            ArrayList<Jugador> jugadoresRanking = juego.ranking();
           
            /*
            String ranking = "";
            for (int i =0; i < jugadoresRanking.size(); i++){
                ranking+=String.valueOf(i+1)+"."+jugadoresRanking.get(i).getNombre()+"\n";
            }
            
            this.rankingTextField.setText(ranking);
            */
            
            this.textNombrePrimerPuesto.setText(jugadoresRanking.get(0).getNombre());
            this.textNombreSegundoPuesto.setText(jugadoresRanking.get(1).getNombre());
            this.textNombreTercerPuesto.setText(jugadoresRanking.get(2).getNombre());
            this.textNombreCuartoPuesto.setText(jugadoresRanking.get(3).getNombre());
            
            this.textSaldoPrimerPuesto.setText(String.valueOf(jugadoresRanking.get(0).getSaldo()));
            this.textSaldoSegundoPuesto.setText(String.valueOf(jugadoresRanking.get(1).getSaldo()));
            this.textSaldoTercerPuesto.setText(String.valueOf(jugadoresRanking.get(2).getSaldo()));
            this.textSaldoCuartoPuesto.setText(String.valueOf(jugadoresRanking.get(3).getSaldo()));
            
            this.panelPrimerPuesto.setBackground(jugadoresRanking.get(0).getColorJugador());
            this.panelSegundoPuesto.setBackground(jugadoresRanking.get(1).getColorJugador());
            this.panelTercerPuesto.setBackground(jugadoresRanking.get(2).getColorJugador());
            this.panelCuartoPuesto.setBackground(jugadoresRanking.get(3).getColorJugador());
            
            this.panelNombrePrimerPuesto.setBackground(jugadoresRanking.get(0).getColorJugador());
            this.panelNombreSegundoPuesto.setBackground(jugadoresRanking.get(1).getColorJugador());
            this.panelNombreTercerPuesto.setBackground(jugadoresRanking.get(2).getColorJugador());
            this.panelNombreCuartoPuesto.setBackground(jugadoresRanking.get(3).getColorJugador());
            
            this.panelSaldoPrimerPuesto.setBackground(jugadoresRanking.get(0).getColorJugador());
            this.panelSaldoSegundoPuesto.setBackground(jugadoresRanking.get(1).getColorJugador());
            this.panelSaldoTercerPuesto.setBackground(jugadoresRanking.get(2).getColorJugador());
            this.panelSaldoCuartoPuesto.setBackground(jugadoresRanking.get(3).getColorJugador());
        }
        
        for (int i = 0; i < casillas.size(); i++)
        {
            switch(i){
                case 0:
                    casillas.get(i).setCasilla(juego.getTablero().getCasillas().get(0));
                    break;
                case 5:
                    casillas.get(i).setCasilla((CasillaSorpresa) (juego.getTablero().getCasillas().get(5)));
                    break;
                case 10:
                    casillas.get(i).setCasilla(juego.getTablero().getCasillas().get(10));
                    break;
                case 15:
                    casillas.get(i).setCasilla((CasillaSorpresa) (juego.getTablero().getCasillas().get(15)));
                    break;
                default:
                    casillas.get(i).setCasilla((CasillaCalle) (juego.getTablero().getCasillas().get(i)));
                    
            }
            casillas.get(i).setBorder(bordePorDefecto);
        }
        
      
        casillas.get(juego.getJugadorActual().getCasillaActual()).setBorder(new LineBorder(juego.getJugadorActual().getColorJugador(),3));
        /*
        this.casillaPanel1.setCasilla(juego.getTablero().getCasillas().get(0));
        this.casillaPanel2.setCasilla((CasillaCalle) (juego.getTablero().getCasillas().get(1)));
        this.casillaPanel3.setCasilla((CasillaCalle) (juego.getTablero().getCasillas().get(2)));
        this.casillaPanel4.setCasilla((CasillaCalle) (juego.getTablero().getCasillas().get(3)));
        this.casillaPanel5.setCasilla((CasillaCalle) (juego.getTablero().getCasillas().get(4)));
        this.casillaPanel6.setCasilla((CasillaSorpresa) (juego.getTablero().getCasillas().get(5)));
        this.casillaPanel7.setCasilla((CasillaCalle) (juego.getTablero().getCasillas().get(6)));
        this.casillaPanel8.setCasilla((CasillaCalle) (juego.getTablero().getCasillas().get(7)));
        this.casillaPanel9.setCasilla((CasillaCalle) (juego.getTablero().getCasillas().get(8)));
        this.casillaPanel10.setCasilla((CasillaCalle) (juego.getTablero().getCasillas().get(9)));
        this.casillaPanel11.setCasilla(juego.getTablero().getCasillas().get(10));
        this.casillaPanel12.setCasilla((CasillaCalle) (juego.getTablero().getCasillas().get(11)));
        this.casillaPanel13.setCasilla((CasillaCalle) (juego.getTablero().getCasillas().get(12)));
        this.casillaPanel14.setCasilla((CasillaCalle) (juego.getTablero().getCasillas().get(13)));
        this.casillaPanel15.setCasilla((CasillaCalle) (juego.getTablero().getCasillas().get(14)));
        this.casillaPanel16.setCasilla((CasillaSorpresa) (juego.getTablero().getCasillas().get(15)));
        this.casillaPanel17.setCasilla((CasillaCalle) (juego.getTablero().getCasillas().get(16)));
        this.casillaPanel18.setCasilla((CasillaCalle) (juego.getTablero().getCasillas().get(17)));
        this.casillaPanel19.setCasilla((CasillaCalle) (juego.getTablero().getCasillas().get(18)));
        this.casillaPanel20.setCasilla((CasillaCalle) (juego.getTablero().getCasillas().get(19)));
        */
        repaint();
        revalidate();
    
    }
}
