/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.CasillaCalle;
import civitas.Jugador;
import civitas.JugadorEspeculador;
import java.util.ArrayList;

/**
 *
 * @author carlo
 */
public class JugadorPanel extends javax.swing.JPanel {

    /**
     * Creates new form JugadorPanel
     */
    Jugador jugador;

    public JugadorPanel() {
        initComponents();
        jugador = null;
    }

    public void setJugador(Jugador jugador) {
        boolean especulador = false;
        this.jugador = jugador;
        this.nombreTextField.setText(jugador.getNombre());
        this.saldoTextField.setText(String.valueOf(jugador.getSaldo()));

        if (jugador instanceof JugadorEspeculador) {
            especulador = true;
        }

        if (especulador) {
            this.jugadorEspeculadorTextField.setText("Si");
        } else {
            this.jugadorEspeculadorTextField.setText("No");
        }
        
        rellenaPropiedades(jugador.getPropiedades());
        repaint();
        revalidate();
    }
    
    private void rellenaPropiedades (ArrayList<CasillaCalle> lista){
        propiedadesPanel.removeAll();
        
        for (CasillaCalle t : lista){
            PropiedadPanel vistaPropiedad = new PropiedadPanel();
            vistaPropiedad.setPropiedad(t);
            
            propiedadesPanel.add(vistaPropiedad);
            vistaPropiedad.setVisible(true);
        }
        
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreLabel = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        saldoLabel = new javax.swing.JLabel();
        saldoTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jugadorEspeculadorTextField = new javax.swing.JTextField();
        propiedadesPanel = new javax.swing.JPanel();

        nombreLabel.setText("Nombre:");
        add(nombreLabel);

        nombreTextField.setEditable(false);
        nombreTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextFieldActionPerformed(evt);
            }
        });
        add(nombreTextField);

        saldoLabel.setText("Saldo:");
        add(saldoLabel);

        saldoTextField.setEditable(false);
        add(saldoTextField);

        jLabel1.setText("¿Jugador Especulador?");
        add(jLabel1);

        jugadorEspeculadorTextField.setEditable(false);
        add(jugadorEspeculadorTextField);

        propiedadesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Propiedades", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP));
        propiedadesPanel.setLayout(new javax.swing.BoxLayout(propiedadesPanel, javax.swing.BoxLayout.Y_AXIS));
        add(propiedadesPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jugadorEspeculadorTextField;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JPanel propiedadesPanel;
    private javax.swing.JLabel saldoLabel;
    private javax.swing.JTextField saldoTextField;
    // End of variables declaration//GEN-END:variables
}
