/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.CasillaCalle;

/**
 *
 * @author carlo
 */
public class PropiedadPanel extends javax.swing.JPanel {

    /**
     * Creates new form PropiedadPanel
     */
    
    CasillaCalle tituloPropiedad;
    
    public PropiedadPanel() {
        initComponents();
    }

    public void setPropiedad(CasillaCalle tituloPropiedad) {
        this.tituloPropiedad = tituloPropiedad;
        this.nombreTextField.setText(tituloPropiedad.getNombre());
        this.casasTextField.setText(String.valueOf(tituloPropiedad.getNumCasas()));
        this.hotelesTextField.setText(String.valueOf(tituloPropiedad.getNumHoteles()));
        
        this.revalidate();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreLabel = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        casasLabel = new javax.swing.JLabel();
        casasTextField = new javax.swing.JTextField();
        hotelesLabel = new javax.swing.JLabel();
        hotelesTextField = new javax.swing.JTextField();

        nombreLabel.setText("Nombre:");
        add(nombreLabel);

        nombreTextField.setEditable(false);
        add(nombreTextField);

        casasLabel.setText("Casas:");
        add(casasLabel);

        casasTextField.setEditable(false);
        add(casasTextField);

        hotelesLabel.setText("Hoteles:");
        add(hotelesLabel);

        hotelesTextField.setEditable(false);
        add(hotelesTextField);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel casasLabel;
    private javax.swing.JTextField casasTextField;
    private javax.swing.JLabel hotelesLabel;
    private javax.swing.JTextField hotelesTextField;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTextField;
    // End of variables declaration//GEN-END:variables
}
